import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { Receipt } from './types.js';

/**
 * Appends a Certificate of Integrity page to the provided PDF buffer.
 * @param pdfBuffer The original PDF document as a Buffer (or Uint8Array).
 * @param receipt The Deed Shield receipt to embed.
 * @returns A promise that resolves to the new PDF buffer with the appended page.
 */
export async function appendIntegrityPage(
  pdfBuffer: Uint8Array,
  receipt: Receipt
): Promise<Uint8Array> {
  // Load the existing PDF
  const pdfDoc = await PDFDocument.load(pdfBuffer);

  // Embed standard font
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // Add a new page (Letter size: 612 x 792)
  const page = pdfDoc.addPage([612, 792]);
  const { width, height } = page.getSize();

  // Color Definitions
  const deepNavy = rgb(0.05, 0.1, 0.2); // Approximate Deep Navy
  const shieldBlue = rgb(0.2, 0.4, 0.8); // Approximate Shield Blue

  // Header: Deed Shield Logo/Title
  page.drawText('Deed Shield', {
    x: 50,
    y: height - 60,
    size: 24,
    font: fontBold,
    color: deepNavy,
  });

  page.drawText('Certificate of Integrity', {
    x: 50,
    y: height - 90,
    size: 18,
    font: font,
    color: shieldBlue,
  });

  // Divider Line
  page.drawLine({
    start: { x: 50, y: height - 110 },
    end: { x: width - 50, y: height - 110 },
    thickness: 2,
    color: deepNavy,
  });

  // Body Text
  const fontSize = 12;
  const lineHeight = 18;
  let yPosition = height - 150;

  const drawLabelValue = (label: string, value: string) => {
    page.drawText(`${label}:`, {
      x: 50,
      y: yPosition,
      size: fontSize,
      font: fontBold,
      color: deepNavy,
    });
    page.drawText(value, {
      x: 200,
      y: yPosition,
      size: fontSize,
      font: font,
      color: rgb(0, 0, 0),
    });
    yPosition -= lineHeight;
  };

  drawLabelValue('Receipt ID', receipt.receiptId);
  drawLabelValue('Receipt Hash', receipt.receiptHash);
  drawLabelValue('Timestamp', receipt.createdAt);
  drawLabelValue('Policy Profile', receipt.policyProfile);
  drawLabelValue('Risk Score', receipt.riskScore.toString());
  drawLabelValue('Decision', receipt.decision);

  yPosition -= lineHeight; // Extra spacing

  // Verification Instructions
  page.drawText('Verification Instructions:', {
    x: 50,
    y: yPosition,
    size: 14,
    font: fontBold,
    color: deepNavy,
  });
  yPosition -= lineHeight * 1.5;

  page.drawText(
    'To verify this document, visit the Deed Shield portal and enter the Receipt ID.',
    {
      x: 50,
      y: yPosition,
      size: 10,
      font: font,
      color: rgb(0.2, 0.2, 0.2),
    }
  );
  yPosition -= lineHeight * 2;

  // Placeholder for "QR Code" (simulated with text bounding box for now)
  // Real implementation would generate a QR code image (e.g. qrcode library) and embed it.
  // For this v1, we just draw a box.
  const qrSize = 100;
  page.drawRectangle({
    x: 50,
    y: yPosition - qrSize,
    width: qrSize,
    height: qrSize,
    borderColor: deepNavy,
    borderWidth: 2,
  });
  
  page.drawText('SCAN TO VERIFY', {
      x: 55,
      y: yPosition - qrSize / 2 - 5,
      size: 10,
      font: fontBold,
      color: deepNavy,
      maxWidth: qrSize - 10
  });

  // Footer
  page.drawText(`Generated by Deed Shield • ${receipt.verifierId}`, {
    x: 50,
    y: 50,
    size: 10,
    font: font,
    color: rgb(0.5, 0.5, 0.5),
  });

  // Save the modified PDF
  const modifiedPdfBytes = await pdfDoc.save();
  return modifiedPdfBytes;
}
