import { Buffer } from 'node:buffer';
import { RiskSignal } from './types.js';

/**
 * Validates PDF metadata and structure for anomalies.
 * Currently a deterministic stub that checks for specific 'bad' metadata patterns.
 */
export async function checkPdfForensics(pdfBuffer: Buffer): Promise<RiskSignal[]> {
    const signals: RiskSignal[] = [];

    // Deterministic Mock Logic regarding PDF content
    // In a real implementation, we would parse the PDF structure (XRef table, trailers, etc.)

    const pdfString = pdfBuffer.toString('latin1'); // specific to PDF binary reading usually

    // 1. Producer Check
    if (pdfString.includes('/Producer (SuspiciousPDFGenerator v1.0)')) {
        signals.push({
            id: 'BAD_PRODUCER',
            description: 'PDF generated by known fraud tool: SuspiciousPDFGenerator',
            severity: 'HIGH'
        });
    }

    // 2. Font Embedding Check (Mock)
    // If we see specific markers indicating broken font tables
    if (pdfString.includes('/FontDescriptor') && !pdfString.includes('/FontFile')) {
        // This is just a heuristic mock
        // signals.push({ ... })
    }

    // 3. Timestamp irregularities
    // Check CreationDate vs ModDate basics
    if (pdfString.includes('/CreationDate (D:20200101)') && pdfString.includes('/ModDate (D:19900101)')) {
        signals.push({
            id: 'INVALID_TIMESTAMPS',
            description: 'Modification date precedes creation date',
            severity: 'MEDIUM'
        });
    }

    return signals;
}
